### ISSUE TITLE
Fails to build on Linux

### ISSUE THREAD

**Issue by kvaidas** [frekky/iodine#26]
Tested on both Ubuntu 16.04 and Fedora 27.
![iodine](https://user-images.githubusercontent.com/7950944/39235451-97c6c652-487e-11e8-9e7c-404b0f14ec71.png)
Am I just missing something on both or is this a bug or something?

**Comment by frekky** [comment]
You may need to install the `check` library (package `check` on Debian/Ubuntu, although I am unsure about Fedora).
It _shouldn't_ break the configure script but apparently it does, so I'll look into fixing that. If installing the package doesn't fix it then I will try to get that done sooner.

**Comment by kvaidas** [comment]
Looks like that didn't change anything on either Fedora or Ubuntu.

**Comment by aaomidi** [comment]
I have the same issue here.

**Comment by frekky** [comment]
I've looked at this again and the successful output of `./configure` (on my machine, running Arch) contains the following: 
```
checking for library containing sd_listen_fds... -lsystemd                              
checking for library containing setcon... no    
checking for setcon... no                    
disabled: selinux                           
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes      
checking for check... no                 
disabled: unit testing                      
checking arpa/inet.h usability... yes                    
checking arpa/inet.h presence... yes
```
Maybe try installing the package `pkg-config`.

**Comment by aaomidi** [comment]
Still the same issue unfortunately.

**Comment by frekky** [comment]
Could you please paste the output of `pkg-config --version` and `autoreconf --version`, also `./configure --version`. Hopefully we can get to the bottom of this.

**Comment by stefy2008c** [comment]
I had the same issue, both with Debian 9 (64 bit) and Xubuntu 18.04 LTS (32 bit).
Installing some packages fixed it: `sudo apt install autoconf automake zlib1g-dev pkg-config check git`.
I hope this can be useful for others.
