### ISSUE TITLE
Botched find/replace for "connected"?

### ISSUE THREAD

**Issue by cebtenzzre** [frekky/iodine#29]
There is a place in client.c where `connected` has been replaced with `this.connected`:
https://github.com/frekky/iodine/blob/62e3437c6ec501a23b1a64f19a9c376a83596623/src/client.c#L2229
And here, though it is just a comment and technically still correct (maybe even intentional):
https://github.com/frekky/iodine/blob/62e3437c6ec501a23b1a64f19a9c376a83596623/src/client.c#L397

The former `this.connected` is not present in the original yarrick iodine; the latter is from a comment that doesn't exist in the original.

**Comment by frekky** [comment]
Haha, yes that probably was done by mistake. One day I'll find time to sit down and fix it.

**Comment by frekky** [comment]
Time was found because this was fixed on the unstable branch. Closing.
