### ISSUE TITLE
-c or --noipcheck ignored

### ISSUE THREAD

**Issue by danielsokolowski** [frekky/iodine#30]
Attempted to update my working yarrick 0.7.0 iodined to frekkys 0.8.0 and found that -c (--noipcheck) option is ignored. Note I am attempting to connect with yarrick 0.7.0 client.

$ ./iodine.exe -f -r -TSRV -m922 -L1 -I4 -P <PASS_REMOVED> <DOMAIN_REMOVED>
Opening device Local Area Connection
Opened IPv4 UDP socket
Opened IPv4 UDP socket
Sending DNS queries for iodine.danols.com to 181.225.231.110
Using DNS type SRV queries
Opened IPv4 UDP socket
Version ok, both using protocol v 0x00000502. You are user #0
Received bad handshake
Retrying login...
Enabling interface 'Local Area Connection'
Setting IP of interface 'Local Area Connection' to 10.0.0.2 (can take a few seco
nds)...

Server tunnel IP is 10.0.0.1
Skipping raw mode
Using EDNS0 extension
Switching upstream to codec Base128
Server switched upstream to codec Base128
Autodetecting downstream codec (use -O to override)
Switching downstream to codec Base128
Server switched downstream to codec Base128
Switching to lazy mode for low-latency
Server switched to lazy mode
Setting downstream fragment size to max 922...
Connection setup complete, transmitting data.
BADIP: Server rejected sender IP address (maybe iodined -c will help), or server kicked us due to timeout. Will exit if no downstream data is received in 60 seconds.
BADIP: Server rejected sender IP address (maybe iodined -c will help), or server kicked us due to timeout. Will exit if no downstream data is received in 60 seconds.

**Comment by frekky** [comment]
Just to check - you are using iodine client and server from the frekky/master branch, which should both be version 0.8.0?

If you are using the yarrick iodine 0.7.0 with the frekky 0.8.0 server, it will definitely not work properly if at all (and _shouldn't_ let you connect, but the version check could be broken depending on which branch you are using).

**Comment by danielsokolowski** [comment]
I'm using yarrick iodine 0.7.0 and (yours) frekky 0.8.0 server. I assumed the version check is what creates backward comptability, the client says I can only do version protocol X and so the server only serves the that version - is this how it supposed to work?

**Comment by frekky** [comment]
@danielsokolowski Yes, I think that is correct, assuming I understand correctly.

Anyway, just to clarify, the version check handshake is the first thing that the client tries to do when connecting to the server and that is the only part of the protocol that is meant to be backwards compatible - that is, if a server receives a version handshake from a client with a different protocol version, it will not allow the client to connect and thus `iodine` will exit with an error. Having said that, I never did any rigourous testing so the version check may have bugs where it doesn't fail correctly in some configurations (and then the client may try to connect anyway and encounter problems elsewhere, which is probably what you are seeing).

Feel free to have a look through the code - if you compile with `make debug` and run with `-DDDDD` you should get plenty of verbose output including line numbers to help see where things are going wrong.
