### ISSUE TITLE
tcp to tcp forward

### ISSUE THREAD

**Issue by hackoon** [frekky/iodine#7]
would be nicer to have tcp to tcp forwarding instead of stdio to tcp, I tried to use socat with rsyncd but it won't work

**Comment by frekky** [comment]
TCP-TCP forwarding is a possibility, but not likely to be implemented soon.

At the moment the whole data transfer process is very unreliable and definitely needs more testing before it can be guaranteed to work with something like rsync. It is likely that the issue is not with the socat/rsync options but with iodine itself (data being corrupted etc).

If you can keep an SSH session open using the ProxyCommand option with iodine in your configuration then it should be possible to use it with rsync and socat. Please let me know the results of your testing.

**Comment by hackoon** [comment]
I rather use use rsyncd  over the tunnel. I would prefer udp port forwarding when the underlying transport is unreliable. Let openvpn or other udp tunnel handle it. I wouldn't mind if the tun interface mode disappears altogether.

**Comment by hackoon** [comment]
If you give me some tip where to start, I would provide a patch for udp port forwarding.

**Comment by frekky** [comment]
That would be excellent. Fork iodine and commit the changes to your fork, then open a pull request when you've got it working.

**Comment by hackoon** [comment]
Can you give me a clue which functions/files to look at?

**Comment by frekky** [comment]
This should be a fairly useful list of functions currently used for TCP forwarding. There are probably a few that I've missed but this should be a good place to start.

On the client side:
- `client.c:949 tunnel_stdin()` reads data from stdin and sends it over DNS to the server
- `client.c:1471 send_login()` sends the server the login hash and the TCP forward IP address/port
- `client.h:34 struct client_instance` has all the stuff in `this` including the TCP forward bits
- `client.c:1645 handshake_login()` checks the TCP forward result from server

Server-side:
- `server.c:639 tunnel_tcp()` reads data from TCP socket, sends to client
- `server.c:909 handle_full_packet()` writes data to TCP socket
- `server.c:1402 handle_dns_login()` opens TCP connection on client login
- `users.h:27 struct tun_user` has the user data including TCP forward details

Also see `doc/proto_00000800.txt` for the protocol details, please update that with any changes you make.

**Comment by hackoon** [comment]
Thanks that will do. Any idea where to open the listening socked in the client?

**Comment by frekky** [comment]
Probably somewhere in `client_handshake()` or a new function called from within that, or perhaps within `handshake_login()`.

**Comment by frekky** [comment]
Since iodine does not provide guaranteed arrival TCP forwarding is obsolete, to be replaced by UDP forwarding at some point.
